### ISSUE TITLE
Getting cwd_global to run again

### ISSUE THREAD

**Issue by stineb** [geco-bern/map2tidy#5] opened 2024-07-25 06:52 UTC
map2tidy is extensively used in `cwd_global()` @patricia264 @Mtrsh . 
After the update, I checked it, trying to run the scripts in that repository (`analysis/`). 
The script `make_tidy_cmip6.R`, throws error:
```
Caused by error in `dplyr::mutate()` at map2tidy/R/helpers.R:262:9:
ℹ In argument: `datetime = CFtime::as_timestamp(...)`.
Caused by error:
! 'as_timestamp' is not an exported object from 'namespace:CFtime'
```
This is not plausible at first sight. `as_timestamp()` seems to be available in CFtime. What could be the issue?

**Comment by fabern** [comment] 2024-07-25 11:25
There was a recent rename of the function from `CFtime::CFtimestamp()` to `CFtime::as_timestamp()` within the CFtime package. Maybe linked to an old version that was loaded?

Can you send me the location of the script `make_tidy_cmip6.R` by PM?

**Comment by fabern** [comment] 2024-07-26 07:04
I can't reproduce this issue.
On my side it works as it should on Workstation 02.

Could you give it a try with this branch: https://github.com/geco-bern/cwd_global/tree/update-for-map2tidy-v2.
Does this run for you? On Workstation 02? Locally?

**Comment by fabern** [comment] 2024-08-20 22:14
I updated `make_tidy_cmip6.R` and all other scripts in the repository https://github.com/geco-bern/cwd_global/tree/update-for-map2tidy-v2 for 'map2tidy'. 

Since it works as it should, I'm now closing this issue.

**Closed by fabern** 2024-08-20 22:14 UTC
